spring:
  datasource:
    url: jdbc:postgresql://1.14.68.40:5432/prompt
    username: prompt
    password: prompt@123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: dev